Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/HashSyntax:
  Enabled: false

Metrics/AbcSize:
  Max: 25
Metrics/LineLength:
  Max: 120
Metrics/CyclomaticComplexity:
  Max: 6
