#!/usr/bin/env ruby

require 'n_cipher'
require 'thor'

class NCipherCLI < Thor
  map %w(-v --version) => :version
  class_option :seed, :type => :string, :default => 'にゃんぱす'
  class_option :delimiter, :type => :string, :default => '〜'

  sub_commands = {'encode' => ['encode <STRING>', '文字列をN暗号化'],
                  'decode' => ['decode <STRING>', 'N暗号文字列を復号化']}

  sub_commands.each_pair do |command, (synopsis, description)|
    desc(synopsis, description)
    define_method(command) do |string = nil|
      begin
        string ||= $stdin.read.chomp
        STDOUT.puts NCipher.send(command, string, seed: options[:seed], delimiter: options[:delimiter])
      rescue => e
        STDERR.puts "#{__FILE__}: #{e.message}"
        exit 1
      end
    end
  end

  desc 'version', 'Print version'
  def version
    STDOUT.puts NCipher::VERSION
    exit 0
  end
end

NCipherCLI.start
